// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "post",
//   description: "Generated by create next app",
// };

export default function PostLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <div>
    //   {children}
    // </div>
      <div className="w-full grid transform translate-x-0 duration-200 ease-in-out
        grid-cols-[minmax(0,_5px),minmax(0,_708px),minmax(0,_5px)] 
        sm:grid-cols-[minmax(96px,_1fr),minmax(0,_708px),minmax(96px,_1fr)] 
        bg-white dark:bg-neutral-950
      ">
        <div className=""></div>
        <div className="max-w-full">
          {children}
        </div>
        <div className=""></div>
      </div>

  );
}
